//! Generate the [`NodeKind`] enum from msf's `generated/ast_kinds.h`.
//!
//! msf ships a single source of truth for AST node kinds — `ast_kinds.h`, itself
//! generated from `data/ast_nodes.def`. Rather than hand-maintain a parallel
//! Rust enum (which drifts and forces `Other(N)` archaeology every time msf adds
//! a kind), we parse that header at build time and emit a complete enum plus the
//! `from_raw`/`name` mappings. New msf kinds appear as named variants for free.

use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // crates/msf -> repo root -> vendor/msf/generated/ast_kinds.h
    let header = manifest_dir
        .join("../../vendor/msf/generated/ast_kinds.h")
        .canonicalize()
        .expect("vendor/msf/generated/ast_kinds.h not found — is the submodule checked out?");

    let text = std::fs::read_to_string(&header).expect("read ast_kinds.h");
    let kinds = parse_kinds(&text);

    let mut out = String::new();
    out.push_str("// @generated by crates/msf/build.rs from vendor/msf/generated/ast_kinds.h\n");
    out.push_str("// DO NOT EDIT — regenerate by touching the header or `cargo build`.\n\n");

    // ── enum ──────────────────────────────────────────────────────────────
    out.push_str("/// What kind of syntax an AST [`Node`](crate::Node) represents.\n");
    out.push_str("///\n");
    out.push_str("/// One variant per msf `ASTNodeKind`, generated from the C header so the\n");
    out.push_str(
        "/// two never drift. [`NodeKind::Other`] is a forward-compatible catch-all for\n",
    );
    out.push_str("/// any kind a future msf adds before this crate is regenerated.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum NodeKind {\n");
    for (_, variant, _) in &kinds {
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("    /// A kind newer than this crate's generated table (raw discriminant).\n");
    out.push_str("    Other(u32),\n");
    out.push_str("}\n\n");

    // ── from_raw ──────────────────────────────────────────────────────────
    out.push_str("impl NodeKind {\n");
    out.push_str("    pub(crate) fn from_raw(raw: msf_sys::ASTNodeKind::Type) -> NodeKind {\n");
    out.push_str("        use msf_sys::ASTNodeKind as K;\n");
    out.push_str("        match raw {\n");
    for (cname, variant, _) in &kinds {
        out.push_str(&format!("            K::{cname} => NodeKind::{variant},\n"));
    }
    out.push_str("            other => NodeKind::Other(other),\n");
    out.push_str("        }\n    }\n\n");

    // ── name ──────────────────────────────────────────────────────────────
    out.push_str("    /// The snake_case kind name (e.g. `\"struct_decl\"`), for dumps.\n");
    out.push_str("    pub fn name(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for (_, variant, snake) in &kinds {
        out.push_str(&format!(
            "            NodeKind::{variant} => \"{snake}\",\n"
        ));
    }
    out.push_str("            NodeKind::Other(_) => \"other\",\n");
    out.push_str("        }\n    }\n}\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("node_kind.rs"), out).expect("write node_kind.rs");

    println!("cargo:rerun-if-changed={}", header.display());
    println!("cargo:rerun-if-changed=build.rs");
}

/// Returns `(C_NAME, VariantName, snake_name)` for every `AST_*` kind except
/// the `AST__COUNT` sentinel, in declaration order.
fn parse_kinds(text: &str) -> Vec<(String, String, String)> {
    let mut kinds = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("AST_") {
            continue;
        }
        // Take the identifier up to the first non-identifier char.
        let cname: String = trimmed
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        if cname == "AST__COUNT" {
            continue;
        }
        let suffix = cname.strip_prefix("AST_").unwrap_or(&cname);
        let snake = suffix.to_ascii_lowercase();
        let variant = pascal_case(suffix);
        kinds.push((cname, variant, snake));
    }
    kinds
}

/// `SOURCE_FILE` -> `SourceFile`, `IDENT_EXPR` -> `IdentExpr`.
fn pascal_case(screaming_snake: &str) -> String {
    screaming_snake
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            let head = chars.next().unwrap().to_ascii_uppercase();
            let tail: String = chars.as_str().to_ascii_lowercase();
            format!("{head}{tail}")
        })
        .collect()
}
