//! Generate the [`NodeKind`] enum from msf's public header, `include/msf.h`.
//!
//! There is exactly one canonical source of truth for AST node kinds that this
//! workspace consumes: the `ASTNodeKind` enum in `vendor/msf/include/msf.h`.
//! That is the header `msf-sys` feeds to bindgen, so the `K::AST_*` constants
//! this crate matches against and the enum we generate variants from are derived
//! from the *same bytes*. Parsing the generated `ast_kinds.h` instead would split
//! the source of truth: `ast_kinds.h` could gain a kind before `msf.h`/bindgen
//! caught up, and this crate would emit match arms against constants `msf-sys`
//! does not expose. Reading the public header keeps the two crates in lockstep.
//!
//! Rather than hand-maintain a parallel Rust enum (which drifts and forces
//! `Other(N)` archaeology every time msf adds a kind), we parse the header at
//! build time and emit a complete enum plus the `from_raw`/`name` mappings. New
//! msf kinds appear as named variants for free.

use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // crates/msf -> repo root -> vendor/msf/include/msf.h — the *same* public
    // header msf-sys bindgens, so NodeKind and the ASTNodeKind constants can
    // never drift apart.
    let header = manifest_dir
        .join("../../vendor/msf/include/msf.h")
        .canonicalize()
        .expect("vendor/msf/include/msf.h not found — is the submodule checked out?");

    let text = std::fs::read_to_string(&header).expect("read msf.h");
    let kinds = parse_kinds(&text);

    let mut out = String::new();
    out.push_str("// @generated by crates/msf/build.rs from vendor/msf/include/msf.h\n");
    out.push_str("// DO NOT EDIT — regenerate by touching the header or `cargo build`.\n\n");

    // ── enum ──────────────────────────────────────────────────────────────
    out.push_str("/// What kind of syntax an AST [`Node`](crate::Node) represents.\n");
    out.push_str("///\n");
    out.push_str("/// One variant per msf `ASTNodeKind`, generated from the C header so the\n");
    out.push_str(
        "/// two never drift. [`NodeKind::Other`] is a forward-compatible catch-all for\n",
    );
    out.push_str("/// any kind a future msf adds before this crate is regenerated.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum NodeKind {\n");
    for (_, variant, _) in &kinds {
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("    /// A kind newer than this crate's generated table (raw discriminant).\n");
    out.push_str("    Other(u32),\n");
    out.push_str("}\n\n");

    // ── from_raw ──────────────────────────────────────────────────────────
    out.push_str("impl NodeKind {\n");
    out.push_str("    pub(crate) fn from_raw(raw: msf_sys::ASTNodeKind::Type) -> NodeKind {\n");
    out.push_str("        use msf_sys::ASTNodeKind as K;\n");
    out.push_str("        match raw {\n");
    for (cname, variant, _) in &kinds {
        out.push_str(&format!("            K::{cname} => NodeKind::{variant},\n"));
    }
    out.push_str("            other => NodeKind::Other(other),\n");
    out.push_str("        }\n    }\n\n");

    // ── name ──────────────────────────────────────────────────────────────
    out.push_str("    /// The snake_case kind name (e.g. `\"struct_decl\"`), for dumps.\n");
    out.push_str("    pub fn name(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for (_, variant, snake) in &kinds {
        out.push_str(&format!(
            "            NodeKind::{variant} => \"{snake}\",\n"
        ));
    }
    out.push_str("            NodeKind::Other(_) => \"other\",\n");
    out.push_str("        }\n    }\n}\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("node_kind.rs"), out).expect("write node_kind.rs");

    println!("cargo:rerun-if-changed={}", header.display());
    println!("cargo:rerun-if-changed=build.rs");
}

/// Returns `(C_NAME, VariantName, snake_name)` for every `AST_*` kind except
/// the `AST__COUNT` sentinel, in declaration order.
///
/// Scoped to the `typedef enum { … } ASTNodeKind;` block so unrelated `AST_*`
/// tokens elsewhere in the public header (macros, prose in doc comments) cannot
/// leak into the generated enum.
fn parse_kinds(text: &str) -> Vec<(String, String, String)> {
    let body = ast_node_kind_enum_body(text);
    let mut kinds = Vec::new();
    for line in body.lines() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("AST_") {
            continue;
        }
        // Take the identifier up to the first non-identifier char.
        let cname: String = trimmed
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        if cname == "AST__COUNT" {
            continue;
        }
        let suffix = cname.strip_prefix("AST_").unwrap_or(&cname);
        let snake = suffix.to_ascii_lowercase();
        let variant = pascal_case(suffix);
        kinds.push((cname, variant, snake));
    }
    assert!(
        !kinds.is_empty(),
        "no AST_* kinds found in the ASTNodeKind enum — has msf.h's enum shape changed?"
    );
    kinds
}

/// Slice out the text between `typedef enum {` and the matching `} ASTNodeKind;`
/// so kind parsing sees only the enumerators, not stray `AST_*` tokens (e.g. the
/// `AST_FOREACH_CHILD` macro or doc-comment prose) elsewhere in the header.
fn ast_node_kind_enum_body(text: &str) -> &str {
    let close = text
        .find("} ASTNodeKind;")
        .expect("`} ASTNodeKind;` not found in msf.h — has the enum been renamed?");
    let before = &text[..close];
    let open = before
        .rfind("typedef enum {")
        .expect("`typedef enum {` preceding ASTNodeKind not found in msf.h");
    &before[open + "typedef enum {".len()..]
}

/// `SOURCE_FILE` -> `SourceFile`, `IDENT_EXPR` -> `IdentExpr`.
fn pascal_case(screaming_snake: &str) -> String {
    screaming_snake
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            let head = chars.next().unwrap().to_ascii_uppercase();
            let tail: String = chars.as_str().to_ascii_lowercase();
            format!("{head}{tail}")
        })
        .collect()
}
