//! A real Rust enum over msf's `ASTNodeKind` constants.
//!
//! Only the kinds the runtime currently distinguishes are named; every other
//! kind maps to [`NodeKind::Other`] carrying msf's raw discriminant, so nothing
//! is lost and matches stay exhaustive. New milestones promote `Other` values to
//! named variants as the evaluator learns to handle them.

/// What kind of syntax an AST [`Node`](crate::Node) represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NodeKind {
    SourceFile,
    Block,
    ExprStmt,
    ReturnStmt,
    ThrowStmt,
    DoStmt,
    DeferStmt,
    CatchClause,
    TryExpr,
    IfStmt,
    GuardStmt,
    ForStmt,
    WhileStmt,
    RepeatStmt,
    SwitchStmt,
    CaseClause,
    BreakStmt,
    ContinueStmt,
    FallthroughStmt,
    VarDecl,
    LetDecl,
    FuncDecl,
    StructDecl,
    ClassDecl,
    ProtocolDecl,
    ExtensionDecl,
    InitDecl,
    DeinitDecl,
    ClosureExpr,
    ClosureCapture,
    CastExpr,
    MacroExpansion,
    EnumDecl,
    EnumCaseDecl,
    EnumElementDecl,
    Conformance,
    SubscriptDecl,
    AccessorDecl,
    InOutExpr,
    TypeInout,
    TypeOptional,
    OptionalBinding,
    OptionalChain,
    ForceUnwrap,
    SubscriptExpr,
    Param,
    CallExpr,
    /// Identifier reference (msf calls this `unresolved_decl_ref_expr`).
    IdentExpr,
    MemberExpr,
    BinaryExpr,
    UnaryExpr,
    AssignExpr,
    ParenExpr,
    TupleExpr,
    TernaryExpr,
    /// A type annotation identifier, e.g. the `Int8` in `let x: Int8`.
    TypeIdent,
    PatternTuple,
    PatternRange,
    PatternWildcard,
    PatternValueBinding,
    PatternEnum,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    BoolLiteral,
    NilLiteral,
    /// Any kind the runtime does not yet name, carrying msf's raw discriminant.
    Other(u32),
}

impl NodeKind {
    pub(crate) fn from_raw(raw: msf_sys::ASTNodeKind::Type) -> NodeKind {
        use msf_sys::ASTNodeKind as K;
        match raw {
            K::AST_SOURCE_FILE => NodeKind::SourceFile,
            K::AST_BLOCK => NodeKind::Block,
            K::AST_EXPR_STMT => NodeKind::ExprStmt,
            K::AST_RETURN_STMT => NodeKind::ReturnStmt,
            K::AST_THROW_STMT => NodeKind::ThrowStmt,
            K::AST_DO_STMT => NodeKind::DoStmt,
            K::AST_DEFER_STMT => NodeKind::DeferStmt,
            K::AST_CATCH_CLAUSE => NodeKind::CatchClause,
            K::AST_TRY_EXPR => NodeKind::TryExpr,
            K::AST_IF_STMT => NodeKind::IfStmt,
            K::AST_GUARD_STMT => NodeKind::GuardStmt,
            K::AST_FOR_STMT => NodeKind::ForStmt,
            K::AST_WHILE_STMT => NodeKind::WhileStmt,
            K::AST_REPEAT_STMT => NodeKind::RepeatStmt,
            K::AST_SWITCH_STMT => NodeKind::SwitchStmt,
            K::AST_CASE_CLAUSE => NodeKind::CaseClause,
            K::AST_BREAK_STMT => NodeKind::BreakStmt,
            K::AST_CONTINUE_STMT => NodeKind::ContinueStmt,
            K::AST_FALLTHROUGH_STMT => NodeKind::FallthroughStmt,
            K::AST_VAR_DECL => NodeKind::VarDecl,
            K::AST_LET_DECL => NodeKind::LetDecl,
            K::AST_FUNC_DECL => NodeKind::FuncDecl,
            K::AST_STRUCT_DECL => NodeKind::StructDecl,
            K::AST_CLASS_DECL => NodeKind::ClassDecl,
            K::AST_PROTOCOL_DECL => NodeKind::ProtocolDecl,
            K::AST_EXTENSION_DECL => NodeKind::ExtensionDecl,
            K::AST_INIT_DECL => NodeKind::InitDecl,
            K::AST_DEINIT_DECL => NodeKind::DeinitDecl,
            K::AST_CLOSURE_EXPR => NodeKind::ClosureExpr,
            K::AST_CLOSURE_CAPTURE => NodeKind::ClosureCapture,
            K::AST_CAST_EXPR => NodeKind::CastExpr,
            K::AST_MACRO_EXPANSION => NodeKind::MacroExpansion,
            K::AST_ENUM_DECL => NodeKind::EnumDecl,
            K::AST_ENUM_CASE_DECL => NodeKind::EnumCaseDecl,
            K::AST_ENUM_ELEMENT_DECL => NodeKind::EnumElementDecl,
            K::AST_CONFORMANCE => NodeKind::Conformance,
            K::AST_SUBSCRIPT_DECL => NodeKind::SubscriptDecl,
            K::AST_ACCESSOR_DECL => NodeKind::AccessorDecl,
            K::AST_INOUT_EXPR => NodeKind::InOutExpr,
            K::AST_TYPE_INOUT => NodeKind::TypeInout,
            K::AST_TYPE_OPTIONAL => NodeKind::TypeOptional,
            K::AST_OPTIONAL_BINDING => NodeKind::OptionalBinding,
            K::AST_OPTIONAL_CHAIN => NodeKind::OptionalChain,
            K::AST_FORCE_UNWRAP => NodeKind::ForceUnwrap,
            K::AST_SUBSCRIPT_EXPR => NodeKind::SubscriptExpr,
            K::AST_PARAM => NodeKind::Param,
            K::AST_CALL_EXPR => NodeKind::CallExpr,
            K::AST_IDENT_EXPR => NodeKind::IdentExpr,
            K::AST_MEMBER_EXPR => NodeKind::MemberExpr,
            K::AST_BINARY_EXPR => NodeKind::BinaryExpr,
            K::AST_UNARY_EXPR => NodeKind::UnaryExpr,
            K::AST_ASSIGN_EXPR => NodeKind::AssignExpr,
            K::AST_PAREN_EXPR => NodeKind::ParenExpr,
            K::AST_TUPLE_EXPR => NodeKind::TupleExpr,
            K::AST_TERNARY_EXPR => NodeKind::TernaryExpr,
            K::AST_PATTERN_TUPLE => NodeKind::PatternTuple,
            K::AST_PATTERN_RANGE => NodeKind::PatternRange,
            K::AST_PATTERN_WILDCARD => NodeKind::PatternWildcard,
            K::AST_PATTERN_VALUE_BINDING => NodeKind::PatternValueBinding,
            K::AST_PATTERN_ENUM => NodeKind::PatternEnum,
            K::AST_TYPE_IDENT => NodeKind::TypeIdent,
            K::AST_INTEGER_LITERAL => NodeKind::IntegerLiteral,
            K::AST_FLOAT_LITERAL => NodeKind::FloatLiteral,
            K::AST_STRING_LITERAL => NodeKind::StringLiteral,
            K::AST_BOOL_LITERAL => NodeKind::BoolLiteral,
            K::AST_NIL_LITERAL => NodeKind::NilLiteral,
            other => NodeKind::Other(other),
        }
    }
}
