//! The runtime-facing AST node vocabulary owned by the frontend.
//!
//! This is the stable `NodeKind` contract the runtime (`quick-swift-core`/
//! `-std`) consumes through [`Node::kind`](crate::Node::kind). The pure-Rust
//! compatibility lowerer in [`crate::compat`] produces these named variants
//! directly; `Other` remains a forward-compatible catch-all.

/// What kind of syntax an AST [`Node`](crate::Node) represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NodeKind {
    Unknown,
    SourceFile,
    FuncDecl,
    VarDecl,
    LetDecl,
    ClassDecl,
    StructDecl,
    EnumDecl,
    ProtocolDecl,
    ExtensionDecl,
    ImportDecl,
    TypealiasDecl,
    InitDecl,
    DeinitDecl,
    ActorDecl,
    Param,
    Attribute,
    OwnershipSpec,
    ThrowsClause,
    AccessorDecl,
    GenericParam,
    WhereClause,
    ProtocolReq,
    Conformance,
    EnumCaseDecl,
    EnumElementDecl,
    SubscriptDecl,
    PrecedenceGroupDecl,
    OperatorDecl,
    PgHigherThan,
    PgLowerThan,
    PgAssociativity,
    PgAssignment,
    PgGroupRef,
    ReturnStmt,
    ThrowStmt,
    IfStmt,
    GuardStmt,
    ForStmt,
    WhileStmt,
    RepeatStmt,
    DoStmt,
    SwitchStmt,
    CaseClause,
    BreakStmt,
    ContinueStmt,
    FallthroughStmt,
    DeferStmt,
    DiscardStmt,
    ExprStmt,
    Block,
    IdentExpr,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    RegexLiteral,
    BoolLiteral,
    NilLiteral,
    CallExpr,
    MemberExpr,
    SubscriptExpr,
    BinaryExpr,
    UnaryExpr,
    ConsumeExpr,
    AssignExpr,
    ParenExpr,
    ArrayLiteral,
    DictLiteral,
    TupleExpr,
    ClosureExpr,
    ClosureCapture,
    TryExpr,
    AwaitExpr,
    CastExpr,
    OptionalChain,
    ForceUnwrap,
    TernaryExpr,
    InoutExpr,
    IfExpr,
    CatchClause,
    KeyPathExpr,
    MacroExpansion,
    AvailabilityExpr,
    TypeIdent,
    TypeOptional,
    TypeArray,
    TypeDict,
    TypeTuple,
    TypeFunc,
    TypeGeneric,
    TypeInout,
    TypeSome,
    TypeAny,
    TypeComposition,
    PatternEnum,
    PatternTuple,
    PatternType,
    PatternGuard,
    PatternRange,
    PatternWildcard,
    PatternValueBinding,
    OptionalBinding,
    /// An `if case`/`guard case`/`while case` pattern-match condition:
    /// children = [pattern, matched expression]. Distinct from
    /// `OptionalBinding`, which only binds a simple `let name = expr`.
    CaseCondition,
    MacroDecl,
    /// A kind newer than this crate's generated table (raw discriminant).
    Other(u32),
}

impl NodeKind {
    pub fn name(self) -> &'static str {
        match self {
            NodeKind::Unknown => "unknown",
            NodeKind::SourceFile => "source_file",
            NodeKind::FuncDecl => "func_decl",
            NodeKind::VarDecl => "var_decl",
            NodeKind::LetDecl => "let_decl",
            NodeKind::ClassDecl => "class_decl",
            NodeKind::StructDecl => "struct_decl",
            NodeKind::EnumDecl => "enum_decl",
            NodeKind::ProtocolDecl => "protocol_decl",
            NodeKind::ExtensionDecl => "extension_decl",
            NodeKind::ImportDecl => "import_decl",
            NodeKind::TypealiasDecl => "typealias_decl",
            NodeKind::InitDecl => "init_decl",
            NodeKind::DeinitDecl => "deinit_decl",
            NodeKind::ActorDecl => "actor_decl",
            NodeKind::Param => "param",
            NodeKind::Attribute => "attribute",
            NodeKind::OwnershipSpec => "ownership_spec",
            NodeKind::ThrowsClause => "throws_clause",
            NodeKind::AccessorDecl => "accessor_decl",
            NodeKind::GenericParam => "generic_param",
            NodeKind::WhereClause => "where_clause",
            NodeKind::ProtocolReq => "protocol_req",
            NodeKind::Conformance => "conformance",
            NodeKind::EnumCaseDecl => "enum_case_decl",
            NodeKind::EnumElementDecl => "enum_element_decl",
            NodeKind::SubscriptDecl => "subscript_decl",
            NodeKind::PrecedenceGroupDecl => "precedence_group_decl",
            NodeKind::OperatorDecl => "operator_decl",
            NodeKind::PgHigherThan => "pg_higher_than",
            NodeKind::PgLowerThan => "pg_lower_than",
            NodeKind::PgAssociativity => "pg_associativity",
            NodeKind::PgAssignment => "pg_assignment",
            NodeKind::PgGroupRef => "pg_group_ref",
            NodeKind::ReturnStmt => "return_stmt",
            NodeKind::ThrowStmt => "throw_stmt",
            NodeKind::IfStmt => "if_stmt",
            NodeKind::GuardStmt => "guard_stmt",
            NodeKind::ForStmt => "for_stmt",
            NodeKind::WhileStmt => "while_stmt",
            NodeKind::RepeatStmt => "repeat_stmt",
            NodeKind::DoStmt => "do_stmt",
            NodeKind::SwitchStmt => "switch_stmt",
            NodeKind::CaseClause => "case_clause",
            NodeKind::BreakStmt => "break_stmt",
            NodeKind::ContinueStmt => "continue_stmt",
            NodeKind::FallthroughStmt => "fallthrough_stmt",
            NodeKind::DeferStmt => "defer_stmt",
            NodeKind::DiscardStmt => "discard_stmt",
            NodeKind::ExprStmt => "expr_stmt",
            NodeKind::Block => "block",
            NodeKind::IdentExpr => "ident_expr",
            NodeKind::IntegerLiteral => "integer_literal",
            NodeKind::FloatLiteral => "float_literal",
            NodeKind::StringLiteral => "string_literal",
            NodeKind::RegexLiteral => "regex_literal",
            NodeKind::BoolLiteral => "bool_literal",
            NodeKind::NilLiteral => "nil_literal",
            NodeKind::CallExpr => "call_expr",
            NodeKind::MemberExpr => "member_expr",
            NodeKind::SubscriptExpr => "subscript_expr",
            NodeKind::BinaryExpr => "binary_expr",
            NodeKind::UnaryExpr => "unary_expr",
            NodeKind::ConsumeExpr => "consume_expr",
            NodeKind::AssignExpr => "assign_expr",
            NodeKind::ParenExpr => "paren_expr",
            NodeKind::ArrayLiteral => "array_literal",
            NodeKind::DictLiteral => "dict_literal",
            NodeKind::TupleExpr => "tuple_expr",
            NodeKind::ClosureExpr => "closure_expr",
            NodeKind::ClosureCapture => "closure_capture",
            NodeKind::TryExpr => "try_expr",
            NodeKind::AwaitExpr => "await_expr",
            NodeKind::CastExpr => "cast_expr",
            NodeKind::OptionalChain => "optional_chain",
            NodeKind::ForceUnwrap => "force_unwrap",
            NodeKind::TernaryExpr => "ternary_expr",
            NodeKind::InoutExpr => "inout_expr",
            NodeKind::IfExpr => "if_expr",
            NodeKind::CatchClause => "catch_clause",
            NodeKind::KeyPathExpr => "key_path_expr",
            NodeKind::MacroExpansion => "macro_expansion",
            NodeKind::AvailabilityExpr => "availability_expr",
            NodeKind::TypeIdent => "type_ident",
            NodeKind::TypeOptional => "type_optional",
            NodeKind::TypeArray => "type_array",
            NodeKind::TypeDict => "type_dict",
            NodeKind::TypeTuple => "type_tuple",
            NodeKind::TypeFunc => "type_func",
            NodeKind::TypeGeneric => "type_generic",
            NodeKind::TypeInout => "type_inout",
            NodeKind::TypeSome => "type_some",
            NodeKind::TypeAny => "type_any",
            NodeKind::TypeComposition => "type_composition",
            NodeKind::PatternEnum => "pattern_enum",
            NodeKind::PatternTuple => "pattern_tuple",
            NodeKind::PatternType => "pattern_type",
            NodeKind::PatternGuard => "pattern_guard",
            NodeKind::PatternRange => "pattern_range",
            NodeKind::PatternWildcard => "pattern_wildcard",
            NodeKind::PatternValueBinding => "pattern_value_binding",
            NodeKind::OptionalBinding => "optional_binding",
            NodeKind::CaseCondition => "case_condition",
            NodeKind::MacroDecl => "macro_decl",
            NodeKind::Other(_) => "other",
        }
    }
}
